<?php

namespace Database\Factories;

use App\Models\Project;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<Project>
 */
class ProjectFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'owner_id' => User::factory(),
            'name' => fake()->unique()->words(2, true),
            'description' => fake()->optional()->paragraph(1),

            // 'created_at' => dateTimeBetween('now'),  migration autogenerated, timestamps()
            // 'updated_at' => dateTimeBetween('now'),  migration autogenerated, timestamps()
            'deleted_at' => fake()->optional()->dateTimeBetween('-1 year', 'now'), // migration softDeletes()
        ];
    }
}
