<?php

namespace Database\Factories;

use App\Enums\TaskPriority;
use App\Enums\TaskStatus;
use App\Models\Project;
use App\Models\Task;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<Task>
 */
class TaskFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'project_id' => Project::factory(),
            'creator_id' => User::factory(),

            'title' => fake()->sentence(4),
            'description' => fake()->optional()->paragraph(),
            'status' => TaskStatus::cases()[array_rand(TaskStatus::cases())],
            'priority' => TaskPriority::cases()[array_rand(TaskPriority::cases())],

            'due_at' => fake()->optional()->dateTimeBetween('now', '+1 year'),
            'completed_at' => fake()->optional()->dateTimeBetween('now', '+1 year'),

            // 'created_at' => dateTimeBetween('now'),  migration autogenerated, timestamps()
            // 'updated_at' => dateTimeBetween('now'),  migration autogenerated, timestamps()
            'deleted_at' => fake()->optional()->dateTimeBetween('-1 year', 'now'), // softDeletes()
        ];
    }
}
