<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Attributes\Hidden;
use Illuminate\Database\Eloquent\Attributes\Table;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Carbon;

/**
 * EA = Eloquent Autogenerated
 * @property string $id UUID EA
 * @property string $owner_id UUID FK
 *
 * @property string $name
 * @property string $description
 *
 * @property Carbon|null $created_at EA
 * @property Carbon|null $updated_at EA
 * @property Carbon|null $deleted_at EA
 */
#[Table(key: 'id', keyType: 'string', incrementing: false)]
#[Fillable(['name', 'description'])]
#[Hidden([])]
final class Project extends Model
{
    use HasFactory;
    use HasUuids, SoftDeletes;

    //#region One-Relations
    /** Project belongsTo one userOwner */
    public function userOwner(): BelongsTo
    {
        return $this->belongsTo(User::class, 'owner_id');
    }
    //#endregion One-Relations


    //#region Many-Relations
    /** Project hasMany tasks */
    public function tasks(): HasMany
    {
        return $this->hasMany(Task::class);
    }

    /** Project hasMany projectInvites */
    public function projectInvites(): HasMany
    {
        return $this->hasMany(ProjectInvite::class);
    }

    /** Project belongsToMany projectMembers */
    public function projectMembers(): BelongsToMany
    {
        return $this->belongsToMany(User::class);
    }
    //#endregion Many-Relations
}