<?php

namespace App\Models;

use App\Enums\ProjectInviteStatus;
use App\Enums\ProjectRole;
use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Attributes\Hidden;
use Illuminate\Database\Eloquent\Attributes\Table;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Carbon;
/**
 * EA = Eloquent Autogenerated
 * @property string $id UUID EA
 * @property string $project_id UUID FK
 * @property string $invited_by UUID FK
 *
 * @property string $email
 * @property string $token
 * @property ProjectRole $role
 * @property ProjectInviteStatus $status
 *
 * @property Carbon|null $expires_at
 * @property Carbon|null $accepted_at
 *
 * @property Carbon|null $created_at EA
 * @property Carbon|null $updated_at EA
 * @property Carbon|null $deleted_at EA
 */
#[Table(key: 'id', keyType: 'string', incrementing: false)]
#[Fillable(['project_id', 'invited_by','email', 'role', 'expires_at'])]
#[Hidden([])]
class ProjectInvite extends Model
{
    use HasFactory;
    use HasUuids, SoftDeletes;

    //#region One-Relations
    /** {@see ProjectInvite} always belongsTo one {@see User} */
    public function userInviter(): BelongsTo
    {
        return $this->belongsTo(User::class, 'invited_by');
    }

    /** {@see ProjectInvite} always belongsTo one {@see Project} */
    public function project(): BelongsTo
    {
        return $this->belongsTo(Project::class);
    }
    //#endregion One-Relations


    //#region Many-Relations
    //#endregion Many-Relations
}
