<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Attributes\Hidden;
use Illuminate\Database\Eloquent\Attributes\Table;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Carbon;

/**
 * EA = Eloquent Autogenerated
 * @property string $id UUID EA
 * @property string $ownerId UUID FK
 * @property string $name
 * @property string $description
 * @property Carbon|null $created_at EA
 * @property Carbon|null $updated_at EA
 */
#[Table(key: 'id', keyType: 'string', incrementing: false)]
#[Fillable(['name', 'description'])]
#[Hidden([])]
final class Project extends Model
{
    use HasFactory;
    use HasUuids, SoftDeletes;

    /** owner_id, User relation */
    public function owner(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }
}