<?php

namespace App\Models;

use App\Enums\TaskPriority;
use App\Enums\TaskStatus;

use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Attributes\Table;
use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Attributes\Hidden;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Carbon;

/**
 * FK = Foreign Key
 * EA = Eloquent Autogenerated
 * @property string $id UUID EA
 * @property string $project_id FK
 * @property string $creator_id FK
 *
 * @property string $title
 * @property string $description
 *
 * @property TaskStatus $status
 * @property TaskPriority $priority
 *
 * @property Carbon|null $due_at
 * @property Carbon|null $completed_at
 *
 * @property Carbon|null $created_at EA
 * @property Carbon|null $updated_at EA
 * @property Carbon|null $deleted_at EA
 */
#[Table(key: 'id', keyType: 'string', incrementing: false)]
#[Fillable(['project_id', 'creator_id', 'title', 'description', 'status', 'priority', 'due_at', 'completed_at'])]
#[Hidden([])]
final class Task extends Model
{
    use HasFactory;
    use HasUuids, SoftDeletes;

    //#region One-Relations
    /** {@see Task} always belongsTo one {@see User} creator */
    public function userCreator(): BelongsTo
    {
        return $this->belongsTo(User::class, 'creator_id');
    }

    /** {@see Task} always belongsTo one {@see Project} */
    public function project(): BelongsTo
    {
        return $this->belongsTo(Project::class);
    }
    //#endregion One-Relations


    //#region Many-Relations
    /** {@see Task} optionally belongsToMany {@see User} via task_assignees */
    public function taskAssignees(): BelongsToMany
    {
        return $this->belongsToMany(User::class, 'task_assignees');
    }
    //#endregion Many-Relations
}