<?php

namespace App\Models;

use App\Enums\TaskPriority;
use App\Enums\TaskStatus;

use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Attributes\Table;
use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Attributes\Hidden;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Support\Carbon;

/**
 * FK = Foreign Key
 * EA = Eloquent Autogenerated
 * @property string $id EA
 * @property string $projectId FK
 * @property string $title
 * @property string $description
 * @property TaskStatus $status
 * @property TaskPriority $priority
 * @property string $creatorId FK
 * @property string $assigneeId FK
 * @property Carbon|null $due_at
 * @property Carbon|null $created_at EA
 * @property Carbon|null $updated_at EA
 */
#[Table(key: 'id', keyType: 'string', incrementing: false)]
#[Fillable(['project_id', 'title', 'description', 'status', 'priority', 'assignee_id', 'due_date'])]
#[Hidden([])]
final class Task extends Model
{
    use HasUuids, HasFactory;

    /** project_id, Project relation */
    public function project(): BelongsTo
    {
        return $this->belongsTo(Project::class);
    }

    /** creator_id, User relation */
    public function creator(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /** assignee_id, User relation */
    public function assignee(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }
}