<?php

namespace App\Models;

use App\Enums\TaskPriority;
use App\Enums\TaskStatus;

use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Attributes\Table;
use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Attributes\Hidden;
use Illuminate\Support\Carbon;

/**
 * EA = Eloquent Autogenerated
 * @property string $id EA
 * @property string $projectId
 * @property string $title
 * @property string $description
 * @property TaskStatus $status
 * @property TaskPriority $priority
 * @property string $creatorId
 * @property string $assigneeId
 * @property Carbon|null $due_at
 * @property Carbon|null $created_at EA
 * @property Carbon|null $updated_at EA
 */
#[Table(key: 'id', keyType: 'string', incrementing: false)]
#[Fillable(['projectId', 'title', 'description', 'status', 'priority', 'assigneeId', 'dueDate'])]
#[Hidden([])]
final class Task extends Model
{
    use HasUuids;
}